version: '3.7'

x-variables: &variables
  ENV_STAGE: local
  BROKER_URL: "broker:29092"
  TOPIC: "python_kafka"
  GROUP_ID: "DEFAULT_GROUP"
  PARTITION_ID: 0


services:
  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    entrypoint: /entrypoint.sh
    volumes:
      - ./consumer/:/usr/src/web/:cached
    environment:
      <<: *variables
    restart: unless-stopped
    networks:
      - microservice_network

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    entrypoint: /entrypoint.sh
    volumes:
      - ./consumer/:/usr/src/web/:cached
    environment:
      <<: *variables
    networks:
      - microservice_network

  stream:
    build:
      context: .
      dockerfile: stream/Dockerfile
    entrypoint: /entrypoint.sh
    volumes:
      - ./stream/:/usr/src/web/:cached
    environment:
      <<: *variables
    networks:
      - microservice_network

networks:
  microservice_network:
    driver: bridge
    name: local_microservice_network
